#!/sbin/openrc-run

description="ke-recv"
name="ke-recv"

depend() {
        before xorg xsession
        need dsme dbus dbus-user
}

start_pre() {
        ebegin "Starting ke-recv presetup"
        /usr/sbin/waitdbus system
        . /tmp/session_bus_address.user
        /usr/sbin/waitdbus session
}

start() {
        ebegin "Starting ke-recv"
        /usr/sbin/ke-recv.sh start
}

stop() {
        eend "Stopping ke-recv"
        /usr/sbin/ke-recv.sh stop
}

