#!/bin/sh

if [ -z "$4" ]; then
	type="$(blkid -c /dev/null -o value -s TYPE $1)"
	[ -z "$type" ] && type="vfat"
elif [ -z "$4" = "fat" ]; then
	type="vfat"
else
	type="$4"
fi

. /etc/default/mount-opts

eval opts="$3,$common_opts,$user_opts,\$${type}_opts"

opts=`echo $opts | sed ':l;s/,,/,/g;tl;s/^,//;s/,$//'`

if [ "$user_fsck" != "0" ]; then
	echo "`date +'%Y-%m-%d %H:%M:%S'`  fsck -a $1" >> /var/log/fsck.log
	fsck -a $1 >> /var/log/fsck.log 2>&1
	echo "" >> /var/log/fsck.log
fi

mount -t "$type" -o "$opts" "$1" "$2" > /dev/null
